export const products = [
    {
      id: 1,
      name: "Skechers Monster | Mashton Men's Sneakers Shoes | White",
      category: "Sneakers",
      price: 75,
      image: "/images/product/sneakers1.png",
      isCart: false,
      quantity: 1,
      description: "Gaya sporty yang berani dan kenyamanan pejalan kaki perkotaan adalah pencapaian total dalam sepatu Skechers Monster - Mashton. Kain tenunan mesh yang lembut, kulit halus dan bagian atas sintetis dalam sneaker pelatihan atletik bertali dengan aksen jahitan dan lapisan luar. Desain midsole bertekstur unik, Air-Cooled Memory Foam insole.",
    },
    {
      id: 2,
      name: "Skechers Delson 3.0 Men's Sneaker | Brown",
      category: "Sneakers",
      price: 20,
      image: "/images/product/sneakers2.png",
      isCart: false,
      quantity: 1,
      description: "Gaya versatile favorit menjadi lebih nyaman dengan sepatu Skechers Delson 3.0 - Cicada. Sepatu bergaya Oxford ini dilengkapi dengan mesh knit yang ringan dan bagian upper sintetis yang halus dengan bagian depan bertali elastis dan insole Skechers Air-Cooled Memory FoamÂ® yang empuk.",
    },
    {
      id: 3,
      name: "SKECHERS ARCH FIT D'LUX MEN'S FITNESS SHOES | NAVY",
      category: "Sneakers",
      price: 17,
      image: "/images/product/sneakers3.png",
      isCart: false,
      quantity: 1,
      description: "Kenyamanan dan dukungan sepanjang hari digabungkan dalam Skechers Relaxed FitÂ®: Arch Fit D'Lux. Slip-on ini dilengkapi upper rajutan berteknologi Stretch FitÂ® dengan insole Arch FitÂ® yang dapat dilepas dan midsole yang empuk.",
    },
    {
      id: 4,
      name: "Sepatu Pumps D'Orsay Recycled Polyester Flare Heel | Maroon",
      category: "High Heels",
      price: 70,
      image: "/images/product/heels2.png",
      isCart: false,
      quantity: 1,
      description: "Ciptakan langkah cemerlang di musim ini dengan sepatu pumps d'Orsay berwarna maroon ini. Warna khas musim gugur ini diperkuat dengan gaya d'Orsay yang timeless. Dengan ankle strap yang adjustable dan flare heels setinggi 12 cm, sepatu ini akan memberikan kesan kaki jenjang untuk setiap outfit musim gugur Anda. Untuk menghadirkan kesan nyaman di musim gugur ini, padukan dengan frilly socks dan light knit untuk memberikan kesan yang lebih lembut.",
    },
    {
      id: 5,
      name: "Sandal Strappy Trapeze Heel | Black",
      category: "High Heels",
      price: 50,
      image: "/images/product/heels1.png",
      isCart: false,
      quantity: 1,
      description: "Sandal strappy ini menambah sentuhan berkelas dan flirty pada outfit Anda. Strap yang halus di bagian vamp menyempurnakan desain square-toed yang lebih berani, menciptakan siluet yang memikat, lengkap dengan ankle strap yang dapat disesuaikan agar ukurannya pas. Dengan finishing hitam dan heels trapeze setinggi 7,5 cm, sandal ini akan membuat kaki Anda terlihat lebih jenjang - sempurna untuk melengkapi tampilan kerja atau dipasangkan dengan maxi dress yang anggun saat kencan.",
    },
    {
      id: 6,
      name: "Dr.Martens ICONS 1460 OLD Unisex Boots | OXBLOOD SMOOTH",
      category: "Boots",
      price: 213,
      image: "/images/product/boots1m.png",
      isCart: false,
      quantity: 1,
      description: "1460 merupakan sepatu boot Dr. Martens asli. DNA-nya yang langsung dapat dikenali bisa terlihat dari: 8 eyes, bahan kulit halus klasik Dr. Martens, grooved sides, heel-loop, jahitan warna kuning, dan sol berbantalan udara yang nyaman. Upper:100% LeatherLining:75% Textile, 25% LeatherSole: 100% PVC",
    },
    {
      id: 7,
      name: "Sepatu Boots Ankle Round -Toe Zip-Up | Lilac Grey",
      category: "Boots",
      price: 80,
      image: "/images/product/boots2w.png",
      isCart: false,
      quantity: 1,
      description: "Dalam warna lilac grey yang keren, ankle boots ini akan menambah warna cantik pada pakaian apa pun dalam sekejap. Menampilkan round toe dan block heela moderat yang membuat siluet boot ankle ini berkelas, desain evergreen ini chic dan elegan. Mudah dikenakan dan bahkan lebih mudah ditata, sepatu ini akan menjadi bahan pokok lemari pakaian selama bertahun-tahun yang akan datang. Tambahkan sentuhan akhir yang serasi dengan warna pada ansambel Anda dengan sepatu boots ini dan tas handbaf yang serasi dengan rona serupa",
    },
    {
      id: 8,
      name: "Sepatu Heeled Mules Sepphe Tweed Metallic Buckle Pointed-Toe | Multi",
      category: "Mules",
      price: 56,
      image: "/images/product/mules1w.png",
      isCart: false,
      quantity: 1,
      description: "Ubah penampilan biasa menjadi luar biasa dengan sepatu mules yang anggun dan elegan ini. Desain fitur pointed-toe yang sleek memberikan sentuhan elegan dan memanjangkan tampilan kaki. Lapisan wol putih memberikan sentuhan visual yang menarik, sementara strap pengikat cokelat cognac dengan detail potongan dan jahitan menambahkan sentuhan kontras yang menawan. Elemen desain ini memberikan sentuhan gaya ekstra pada sepatu ini, menjadikannya sebagai pernyataan fashion yang berkelas.",
    }
  ];